version: 2
jobs:
  testbootstrapuser:
    working_directory: ~/porter_testing
    machine:
      enabled: false
    docker:
      - image: circleci/builder-base
    steps:
      - checkout
      - run:
          name: Deps
          command: apt-get update && apt-get install -y curl gcc
      - run:
          name: TestUserBootstrap
          command: export SH=/bin/bash && ~/porter_testing/bin/porter bootstrap --set-usertree=yes
  testbootstrapglobal:
    working_directory: ~/porter_testing
    docker:
      - image: circleci/builder-base
    steps:
      - checkout
      - run:
          name: Deps
          command: apt-get update && apt-get install -y curl gcc
      - run:
          name: TestGlobalBootstrap
          command: export SH=/bin/bash && sudo ~/porter_testing/bin/porter bootstrap
#  testbootstrapmac:
 #   macos:
  #    xcode: "9.3.0"
   # working_directory: ~/porter_testing
    #steps:
     # - checkout
      #- run:
       #   name: XCodeInstall
        #  command: echo "Placeholder"
      #- run:
       #   name: TestUserBootstrap
        #  command: export SH=/bin/bash && ~/porter_testing/bin/porter bootstrap --set-usertree=yes
workflows:
  version: 2
  Testflow:
    jobs:
      - testbootstrapuser
      - testbootstrapglobal
    #  - testbootstrapmac
