version: 2
jobs:
  build:
    working_directory: ~/porter_testing
    machine:
      enabled: false
    docker:
      - image: circleci/builder-base
    steps:
      - checkout
      - run:
          name: Deps
          command: apt-get update && apt-get install -y curl
      - run:
          name: TestUserBootstrap
          command: export SH=/bin/bash && ~/porter_testing/bin/porter bootstrap --set-usertree=yes
      - run:
          name: TestGlobalBootstrap
          command: export SH=/bin/bash && sudo ~/porter_testing/bin/porter bootstrap
