version: 2
jobs:
  testbootstrapuser:
    working_directory: ~/porter_testing
    docker:
      - image: circleci/builder-base
    steps:
      - checkout
      - run:
          name: Deps
          command: apt-get update && apt-get install -y curl gcc build-essential
      - run:
          name: shittyworkaroundfortestingincircleci
          command: rm /bin/sh && ln -s /bin/bash /bin/sh
      - run:
          name: TestUserBootstrap
          command: ~/porter_testing/bin/porter bootstrap --set-usertree=yes
  testbootstrapglobal:
    working_directory: ~/porter_testing
    docker:
      - image: circleci/builder-base
    steps:
      - checkout
      - run:
          name: Deps
          command: apt-get update && apt-get install -y curl gcc build-essential
      - run:
          name: shittyworkaroundfortestingincircleci
          command: rm /bin/sh && ln -s /bin/bash /bin/sh
      - run:
          name: TestGlobalBootstrap
          command: sudo ~/porter_testing/bin/porter bootstrap
workflows:
  version: 2
  Testflow:
    jobs:
      - testbootstrapuser
      - testbootstrapglobal
